export type AllDocsPages =
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenless-developedFuture Proof Package and Import System.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenless-developedRelated Work.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenless-developedRFC Modal Models (first draft).md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenless-developedRunning Benchmarks.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenless-developedTiming Analysis.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenless-developedTools.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenpreliminaryContainerized Execution.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenpreliminaryDistributed Execution.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenpreliminaryGeneric Types, Interfaces, and Inheritance.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenpreliminaryImport System.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenpreliminaryTarget-Supported Features.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenpreliminaryTracing.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyenpreliminaryWriting Reactors in Rust (WIP).md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsContributing.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsOverview.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsPublications and Presentations.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsRegression Tests.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsTutorial.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsWriting Reactors in C++.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsWriting Reactors in C.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsWriting Reactors in Python.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsWriting Reactors in TypeScript.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsdownload-and-buildDeveloper Eclipse Setup with Oomph.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsdownload-and-buildDeveloper IntelliJ Setup (for Kotlin).md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicsdownload-and-buildDownloading and Building.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicslanguage-specificationLanguage Specification.md"
  | "D:DocumentsGitHubLingua Franca Websitelf-lang.github.iopackagesdocumentationcopyen\topicslanguage-specificationMultiports and Banks.md";
