export type AllDocsPages =
  | "less-developed/Future Proof Package and Import System.md"
  | "less-developed/RFC Modal Models (first draft).md"
  | "less-developed/Related Work.md"
  | "less-developed/Running Benchmarks.md"
  | "less-developed/Timing Analysis.md"
  | "less-developed/Tools.md"
  | "preliminary/Containerized Execution.md"
  | "preliminary/Distributed Execution.md"
  | "preliminary/Generic Types, Interfaces, and Inheritance.md"
  | "preliminary/Import System.md"
  | "preliminary/Target-Supported Features.md"
  | "preliminary/Tracing.md"
  | "preliminary/Writing Reactors in Rust (WIP).md"
  | "topics/Contributing.md"
  | "topics/Overview.md"
  | "topics/Regression Tests.md"
  | "topics/Tutorial.md"
  | "topics/Writing Reactors in C++.md"
  | "topics/Writing Reactors in C.md"
  | "topics/Writing Reactors in Python.md"
  | "topics/Writing Reactors in TypeScript.md"
  | "topics/download-and-build/Developer Eclipse Setup with Oomph.md"
  | "topics/download-and-build/Developer IntelliJ Setup (for Kotlin).md"
  | "topics/download-and-build/Downloading and Building.md"
  | "topics/language-specification/Language Specification.md"
  | "topics/language-specification/Multiports and Banks.md";
